---
title: "Figure X"
author: Raphael Eisenhofer
date: 25/7/2023
output:
  md_document:
    variant: markdown_github
---

## Code for figure X

### Raphael Eisenhofer 25/7/2023

## Load packages and data in, set theme
```{r message = FALSE}
library(tidyverse)
library(janitor)

df <- read_delim("../data/DataTable.csv", delim = ',') %>%
  clean_names() %>%
  mutate(year = str_extract(study_id, "[:digit:].*"))

```


## Plot of studies through time
```{r}
#Get counts of publications per year
df %>%
  filter(year != "2023") %>%
  group_by(year) %>%
  summarise(publications = n()) %>%
#Line plot it
  ggplot(aes(x = year, y = publications, group = 1)) +
  geom_line() +
  geom_point() +
  theme_minimal()

```
## Plot of studies through time (controls vs. none)
```{r}
# Get counts of sequenced negative controls
seq_neg_controls <- df %>%
  group_by(year, were_the_negative_controls_sequenced) %>%
  summarise(count = n()) %>%
  filter(were_the_negative_controls_sequenced == "Yes")

#Get counts of publications per year
df %>%
  filter(year != "2023") %>%
  group_by(year, were_there_negative_controls) %>%
  summarise(publications = n()) %>%
  ggplot(aes(x = year, y = publications, 
             group = were_there_negative_controls, 
             colour = were_there_negative_controls)) +
  geom_line(size = 2) +
  geom_text(data = seq_neg_controls, 
            aes(x = year, y = count, label = count), 
            inherit.aes = FALSE) +
  theme_classic() +
  theme(
    legend.position = c(0.3, 0.8),
    axis.title = element_text(size = 14)
  ) +
  labs(x = "Year", y = "Studies (n)", colour = "Negative controls?")


```
